name: GitHub pages

on:
  push:
    branches:
      - qa-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ../source
          recurse: true
          output_dir: ../docs
          config_file: jsdoc.json
